// <auto-generated />
using System;
using FaultDesk.Infrastructure.Persistence;
using Microsoft.Data.SqlTypes;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FaultDesk.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(FaultDeskDbContext))]
    [Migration("20260916091000_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FaultDesk.Domain.Diagnostics.Investigation", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("ReportMarkdown")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("TicketId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("TicketId");

                    b.ToTable("Investigations", (string)null);
                });

            modelBuilder.Entity("FaultDesk.Domain.Tickets.FaultTicket", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CustomerContact")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("CustomerName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<string>("Reference")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Registration")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("nvarchar(7)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("Reference")
                        .IsUnique();

                    b.HasIndex("Registration");

                    b.HasIndex("Status");

                    b.ToTable("FaultTickets", (string)null);
                });

            modelBuilder.Entity("FaultDesk.Infrastructure.Persistence.Entities.TicketEmbedding", b =>
                {
                    b.Property<Guid>("TicketId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("ModelId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<SqlVector<float>>("Vector")
                        .HasColumnType("vector(1536)");

                    b.HasKey("TicketId");

                    b.HasIndex("ModelId");

                    b.ToTable("TicketEmbeddings", (string)null);
                });

            modelBuilder.Entity("FaultDesk.Domain.Diagnostics.Investigation", b =>
                {
                    b.HasOne("FaultDesk.Domain.Tickets.FaultTicket", null)
                        .WithMany()
                        .HasForeignKey("TicketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("FaultDesk.Domain.Diagnostics.AiCallMetadata", "Metadata", b1 =>
                        {
                            b1.Property<Guid>("InvestigationId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<long>("Duration")
                                .HasColumnType("bigint")
                                .HasColumnName("DurationTicks");

                            b1.Property<int?>("InputTokens")
                                .HasColumnType("int")
                                .HasColumnName("InputTokens");

                            b1.Property<string>("Model")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("AiModel");

                            b1.Property<int?>("OutputTokens")
                                .HasColumnType("int")
                                .HasColumnName("OutputTokens");

                            b1.Property<string>("PromptVersion")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("nvarchar(50)")
                                .HasColumnName("PromptVersion");

                            b1.Property<string>("Provider")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("nvarchar(50)")
                                .HasColumnName("AiProvider");

                            b1.Property<bool>("WebSearchUsed")
                                .HasColumnType("bit")
                                .HasColumnName("WebSearchUsed");

                            b1.HasKey("InvestigationId");

                            b1.ToTable("Investigations");

                            b1.WithOwner()
                                .HasForeignKey("InvestigationId");
                        });

                    b.Navigation("Metadata")
                        .IsRequired();
                });

            modelBuilder.Entity("FaultDesk.Domain.Tickets.FaultTicket", b =>
                {
                    b.OwnsOne("FaultDesk.Domain.Tickets.Resolution", "Resolution", b1 =>
                        {
                            b1.Property<Guid>("FaultTicketId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Notes")
                                .IsRequired()
                                .HasMaxLength(2000)
                                .HasColumnType("nvarchar(2000)")
                                .HasColumnName("ResolutionNotes");

                            b1.Property<DateTimeOffset>("ResolvedAt")
                                .HasColumnType("datetimeoffset")
                                .HasColumnName("ResolvedAt");

                            b1.HasKey("FaultTicketId");

                            b1.ToTable("FaultTickets");

                            b1.WithOwner()
                                .HasForeignKey("FaultTicketId");
                        });

                    b.OwnsOne("FaultDesk.Domain.Tickets.TriageSummary", "Triage", b1 =>
                        {
                            b1.Property<Guid>("FaultTicketId")
                                .HasColumnType("uniqueidentifier");

                            b1.PrimitiveCollection<string>("AdviserQuestions")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("TriageAdviserQuestions");

                            b1.Property<string>("Category")
                                .IsRequired()
                                .HasMaxLength(30)
                                .HasColumnType("nvarchar(30)")
                                .HasColumnName("TriageCategory");

                            b1.Property<string>("CustomerSummary")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("nvarchar(500)")
                                .HasColumnName("TriageCustomerSummary");

                            b1.PrimitiveCollection<string>("LikelySystems")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("TriageLikelySystems");

                            b1.Property<string>("SafeToDrive")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("nvarchar(20)")
                                .HasColumnName("TriageSafeToDrive");

                            b1.Property<string>("Severity")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("nvarchar(20)")
                                .HasColumnName("TriageSeverity");

                            b1.PrimitiveCollection<string>("Symptoms")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("TriageSymptoms");

                            b1.Property<string>("Title")
                                .IsRequired()
                                .HasMaxLength(120)
                                .HasColumnType("nvarchar(120)")
                                .HasColumnName("TriageTitle");

                            b1.HasKey("FaultTicketId");

                            b1.ToTable("FaultTickets");

                            b1.WithOwner()
                                .HasForeignKey("FaultTicketId");
                        });

                    b.OwnsOne("FaultDesk.Domain.Vehicles.VehicleDetails", "Vehicle", b1 =>
                        {
                            b1.Property<Guid>("FaultTicketId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int?>("EngineSizeCc")
                                .HasColumnType("int")
                                .HasColumnName("VehicleEngineSizeCc");

                            b1.Property<string>("FuelType")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("nvarchar(20)")
                                .HasColumnName("VehicleFuelType");

                            b1.Property<string>("Make")
                                .IsRequired()
                                .HasMaxLength(60)
                                .HasColumnType("nvarchar(60)")
                                .HasColumnName("VehicleMake");

                            b1.Property<string>("Model")
                                .IsRequired()
                                .HasMaxLength(60)
                                .HasColumnType("nvarchar(60)")
                                .HasColumnName("VehicleModel");

                            b1.Property<string>("Variant")
                                .HasMaxLength(80)
                                .HasColumnType("nvarchar(80)")
                                .HasColumnName("VehicleVariant");

                            b1.Property<int>("Year")
                                .HasColumnType("int")
                                .HasColumnName("VehicleYear");

                            b1.HasKey("FaultTicketId");

                            b1.ToTable("FaultTickets");

                            b1.WithOwner()
                                .HasForeignKey("FaultTicketId");
                        });

                    b.Navigation("Resolution");

                    b.Navigation("Triage");

                    b.Navigation("Vehicle")
                        .IsRequired();
                });

            modelBuilder.Entity("FaultDesk.Infrastructure.Persistence.Entities.TicketEmbedding", b =>
                {
                    b.HasOne("FaultDesk.Domain.Tickets.FaultTicket", "Ticket")
                        .WithOne()
                        .HasForeignKey("FaultDesk.Infrastructure.Persistence.Entities.TicketEmbedding", "TicketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ticket");
                });
#pragma warning restore 612, 618
        }
    }
}
